# Docker Compose file for a Baikal server

services:
  baikal:
    image: bwiedmann/baikal:nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific
      - ssl:/etc/nginx/ssl

volumes:
  config:
  data:
  ssl:
